dropbox:
      access_token: ${dropboxToken:? Cant find access token}
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
      mongodb:
        uri: mongodb://localhost/admin
        username: ${dbuser:admin}
        password: ${dbpassword:admin}
app:
  auth:
    secret: ${JWT_SECRET:Secret1234}
    token_expiration: 8640000000
server:
  port: 10000
